### ISSUE TITLE
under hexo 3.0 is not working

### ISSUE THREAD

**Issue by derekhe** [coneycode/hexo-git-backup#3]
➜  blog  hexo backup
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
ReferenceError: hexo is not defined
  at Hexo.module.exports (/Users/sche/blog/node_modules/hexo-git-backup/backup.js:7:16)
  at Hexo.tryCatcher (/Users/sche/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
  at Hexo.ret (<anonymous>:13:39)
  at /Users/sche/blog/node_modules/hexo/lib/hexo/index.js:192:9
  at tryCatcher (/Users/sche/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
  at Promise._resolveFromResolver (/Users/sche/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:427:31)
  at new Promise (/Users/sche/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:53:37)
  at Hexo.call (/Users/sche/blog/node_modules/hexo/lib/hexo/index.js:188:10)
  at runHexoCommand (/usr/local/lib/node_modules/hexo-cli/lib/index.js:58:17)
  at tryCatcher (/Users/sche/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
  at Promise._settlePromiseFromHandler (/Users/sche/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
  at Promise._settlePromiseAt (/Users/sche/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
  at Promise._settlePromises (/Users/sche/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
  at Async._drainQueue (/Users/sche/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:79:16)
  at Async._drainQueues (/Users/sche/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/Users/sche/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
  at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by coneycode** [comment]
I will solve it tomorrow.

**Comment by lanmeng-org** [comment]
希望能解决，这个插件用着很不错

**Comment by coneycode** [comment]
好的。他的hexo3.0的架构都变了，也没给什么说明文档，我上次中午看了看没改好，后来忙忘了。。我明天再看看。。

**Comment by derekhe** [comment]
我本来也想改一改的，结果发现好像3.0的架构改的很多，所以无力吐槽。。。哥，看你的了

**Comment by coneycode** [comment]
哎，架构改了也就算了。。竟然还没文档。。我去读他的源代码了。。祝我成功。。。

**Comment by derekhe** [comment]
成功了么？亲：）

**Comment by whzecomjm** [comment]
等更新，支持hexo 3.0

**Comment by coneycode** [comment]
support hexo 3.0 now, please update later.
