### ISSUE TITLE
未知报错

### ISSUE THREAD

**Issue by Coolkkmeat** [coneycode/hexo-git-backup#38]
INFO  Start backup: git
INFO  Setting up Git-Backup deployment...
INFO  E:\OneDrive\Blog\themes\butterfly\.git
INFO  First
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: spawn rm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn rm',
  path: 'rm',
  spawnargs: [ '-rf', '.git' ]
}

**Comment by Delta-in-hub** [comment]
同样的问题

**Comment by TRHX** [comment]
参考 https://github.com/coneycode/hexo-git-backup/issues/27
