### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by Liaoer** [coneycode/hexo-git-backup#4]
ERROR Plugin load failed: hexo-git-backup
SyntaxError: Unexpected token var
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (/Users/hrj/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/hrj/blog/node_modules/hexo-git-backup/index.js:10:66
    at /Users/hrj/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/hrj/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/hrj/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/hrj/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/hrj/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/hrj/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/Users/hrj/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/Users/hrj/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:419:13)

**Comment by yanyuechuixue** [comment]
我也遇到了..

**Comment by coneycode** [comment]
因为，3.0还没有做适配。。然后，升级hexo3.0真的挺坑。。

**Comment by coneycode** [comment]
bug fix, please update later.
