### ISSUE TITLE
Windows适配请求

### ISSUE THREAD

**Issue by greenhandzdl** [coneycode/hexo-git-backup#48]
PS D:\GitHub\hexo.bak> hexo b
INFO  Validating config
INFO  DPlayer.min.css is not found in this version of dplayer, skip it.
INFO  Start backup: git
[
  [ 'add', '-A' ],
  [ 'add', 'D:\\GitHub\\hexo.bak\\themes\\Kratos-Rebirth\\*' ]
]
INFO  D:\GitHub\hexo.bak\themes\Kratos-Rebirth\.git
events.js:352
      throw er; // Unhandled 'error' event
      ^

Error: spawn rm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn rm',
  path: 'rm',
  spawnargs: [ '-rf', '.git' ]
}
PS D:\GitHub\hexo.bak>

**Comment by ghost** [comment]
直接改源码
把node_modules\hexo-git-backup\git.js line 53改成
```
var child = spawn('rm .git -Recurse -Force', [],{cwd: themeDir, shell:true});
```
再试试?

**Comment by greenhandzdl** [comment]
OK，就是后面del之后不动了
