### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by SeveNOlogy7** [coneycode/hexo-git-backup#5]
执行 hexo b 之后
TypeError: Cannot read property 'backup' of undefined
    at Hexo.module.exports (/var/www/hx/node_modules/hexo-git-backup/backup.js:8:27)
    at Hexo.tryCatcher (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Hexo.ret (eval at <anonymous> (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/promisify.js:154:12), <anonymous>:12:39)
    at /var/www/hx/node_modules/hexo/lib/hexo/index.js:192:9
    at tryCatcher (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._resolveFromResolver (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/promise.js:427:31)
    at new Promise (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/promise.js:53:37)
    at Hexo.call (/var/www/hx/node_modules/hexo/lib/hexo/index.js:188:10)
    at runHexoCommand (/usr/lib/node_modules/hexo/node_modules/hexo-cli/lib/index.js:58:17)
    at tryCatcher (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/async.js:177:16)
    at Async._drainQueues (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/async.js:187:10)
    at Async.drainQueues (/var/www/hx/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)

**Comment by coneycode** [comment]
bug fix, please update later.
