### ISSUE TITLE
ERROR Plugin load failed: hexo-git-backup

### ISSUE THREAD

**Issue by ye-fight** [coneycode/hexo-git-backup#6]
ERROR Plugin load failed: hexo-git-backup
SyntaxError: Unexpected token var
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (/home/jason-ye/blog/node_modules/hexo/lib/hexo/index.js:213:21)
    at /home/jason-ye/blog/node_modules/hexo-git-backup/index.js:10:66
    at /home/jason-ye/blog/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/home/jason-ye/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/jason-ye/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/jason-ye/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/home/jason-ye/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/home/jason-ye/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:182:16)
    at Async._drainQueues (/home/jason-ye/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:192:10)
    at Async.drainQueues (/home/jason-ye/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:415:13)

**Comment by whzecomjm** [comment]
same error!

**Comment by coneycode** [comment]
bug fix, please update later.

**Comment by ye-fight** [comment]
给力啊，终于修复了……

**Comment by coneycode** [comment]
恩，一直忙，没空修，欢迎试用-_-!
